server:
  port: ${PORT:8080}

spring:
  application:
    name: Polling-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


---
#Dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/polling_db
    username: root
    password: ${my_sql_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true

app:
  cors:
    allowed-origin: http://localhost:3000,http://localhost:5173

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      pollingapp:
        backend: DEBUG
---
#prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  cors:
    allowed-origin: ${ALLOWED_ORIGINS}


logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      pollingapp:
        backend: INFO
